### ISSUE TITLE
 logout button is unclickable in the admin dashboard

### ISSUE THREAD

**Issue by sangamdumre** [anupdangi21/LocalFarmers2#32]
Encountering an unclickable logout button in the admin dashboard disrupts workflow. Steps to address it include confirming cross-device consistency, inspecting code for errors, checking permissions, and clearing cache/cookies. Consider updates or rollbacks, report the bug to the dev team, and employ temporary workarounds like manual cookie clearing until resolved.

**Comment by anupdangi21** [comment]
Thank you for addressing the unclickable logout button in the admin dashboard.
i have addressed that issue and worked on it and i have fixed this issue, now the logout button is clickable
