### ISSUE TITLE
After logging in, clicking on "navigate" directly leads to the logout

### ISSUE THREAD

**Issue by sangamdumre** [anupdangi21/LocalFarmers2#33]
Navigating to the homepage after logging in results in the logout state being immediately reached, which causes unexpected behavior. Check for mistakes in the navigation logic and make sure it leads to the correct place. Look for any session management problems or incorrect code that can cause an early logout.

**Comment by AB-octo** [comment]
Reviewed the navigation logic and identified the incorrect conditional statement triggering the logout state. Also corrected the conditional statement to ensure the logout state is not reached when navigating to the homepage after a successful login and conducted thorough testing to verify the fix and ensure consistent behavior.
