### ISSUE TITLE
 The checkout button is not properly functional in fruit and vegetable

### ISSUE THREAD

**Issue by sangamdumre** [anupdangi21/LocalFarmers2#39]
If the checkout button isn't working properly for fruit and vegetable purchases, check the button's HTML and JavaScript implementation for errors. Ensure it's correctly linked to the checkout process and that backend processes, like payment processing and inventory updates, are functioning. Test across different browsers to see if it's browser-specific.

**Comment by AB-octo** [comment]
The checkout button functionality has been fixed. Now, upon checkout completion, a popup displays the products that have been purchased.
